/**
 * pow3r.control - Sample XMAP v7 Data
 *
 * Purpose:
 * - Development/testing data based on the real pow3r platform architecture
 * - Demonstrates all XMAP v7 features: nodes, edges, workflows, guardian gates
 *
 * Agent Instructions:
 * - This is real architectural data from the Pow3r platform, not mock data
 * - Modeled after configs/pow3r.xmap.pimp.v7.config.json
 */
import type { XmapV7Config } from './types'

export const SAMPLE_CONFIG: XmapV7Config = {
  metadata: {
    id: 'pow3r-platform-v7',
    version: '1.0.0',
    created_at: '2026-02-25T00:00:00Z',
    created_by: 'pow3r.control',
    last_modified_at: '2026-02-25T00:00:00Z',
    last_modified_by: 'pow3r.control',
  },
  manifest: {
    manifest_id: 'pow3r-platform-manifest',
    manifest_version: '1.0.0',
    manifest_status: 'deployed',
    required_gates: [
      'contextLoadedGate',
      'verifiableEvidenceGate',
      'workflowTestsGate',
      'preDeploymentChecksGate',
    ],
  },
  directorAgent: 'maxi',
  nodes: [
    {
      node_id: 'pow3r-config',
      node_type: 'service',
      name: 'pow3r.config',
      description: 'Central configuration and orchestration hub. Hosts MCP servers, workflows, Guardian system.',
      tech_stack: ['Cloudflare Workers', 'Hono', 'Durable Objects', 'D1'],
      deployment_targets: ['cloudflare'],
      status: 'healthy',
      owner: 'platform-team',
      required_tests: ['wf-config-validation'],
      telemetry_endpoints: ['/mcp/xlog'],
    },
    {
      node_id: 'pkg-knowledge',
      node_type: 'data',
      name: 'PKG Knowledge Graph',
      description: '3,127 documents, 3,938 edges. Central knowledge store for the platform.',
      tech_stack: ['Cloudflare Workers', 'D1', 'Vectorize'],
      deployment_targets: ['cloudflare'],
      status: 'healthy',
      owner: 'platform-team',
      telemetry_endpoints: ['/mcp/pkg/xlog'],
    },
    {
      node_id: 'xmap-server',
      node_type: 'mcp_server',
      name: 'XMAP MCP Server',
      description: 'Architecture mapping and visualization data service.',
      tech_stack: ['Hono', 'Durable Objects'],
      deployment_targets: ['cloudflare'],
      status: 'validated',
      owner: 'platform-team',
      required_tests: ['wf-xmap-validation'],
    },
    {
      node_id: 'guardian-system',
      node_type: 'observer',
      name: 'Guardian System',
      description: '19 deployment gates, 12 constitutional articles. Enforcement engine.',
      tech_stack: ['Cloudflare Workers', 'Guardian Gates'],
      deployment_targets: ['cloudflare'],
      status: 'healthy',
      owner: 'platform-team',
    },
    {
      node_id: 'x-system',
      node_type: 'observer',
      name: 'X-System',
      description: 'Unified observability: X-Plugin, X-Log, X-Files, X-Stream, JSON Chain.',
      tech_stack: ['Cloudflare Workers', 'D1', 'Analytics Engine'],
      deployment_targets: ['cloudflare'],
      status: 'healthy',
      owner: 'platform-team',
      telemetry_endpoints: ['/mcp/xplugin', '/mcp/xlog', '/mcp/xfiles', '/mcp/xstream'],
    },
    {
      node_id: 'pow3r-pass',
      node_type: 'gateway',
      name: 'Pow3r Pass',
      description: 'Secure credential management via PASS_KEY. ACL enforcement.',
      tech_stack: ['Cloudflare Workers', 'KV'],
      deployment_targets: ['cloudflare'],
      status: 'healthy',
      owner: 'platform-team',
      privileges: { read: 'authenticated', write: 'admin' },
    },
    {
      node_id: 'director-agent',
      node_type: 'agent',
      name: 'Director of Engineering',
      description: 'Configurable director agent. Resolved from config.directorAgent.',
      tech_stack: ['Cloudflare Workers', 'Pass MCP'],
      deployment_targets: ['cloudflare'],
      status: 'validated',
      owner: 'platform-team',
      privileges: { read: 'public', propose: 'director', execute: 'director' },
    },
    {
      node_id: 'plan-memory',
      node_type: 'data',
      name: 'Plan Memory',
      description: 'Canonical plan index. Tracks all plans with implementation level and status.',
      tech_stack: ['Cloudflare Workers', 'D1'],
      deployment_targets: ['cloudflare'],
      status: 'healthy',
      owner: 'platform-team',
    },
    {
      node_id: 'pow3r-control',
      node_type: 'ui',
      name: 'pow3r.control',
      description: 'Omnimedia orchestration control surface. 3D/2D XMAP visualization.',
      tech_stack: ['React', 'Vite', 'TailwindCSS', 'Three.js', 'R3F'],
      deployment_targets: ['cloudflare-pages'],
      status: 'deploying',
      owner: 'platform-team',
    },
    {
      node_id: 'component-factory',
      node_type: 'component_factory',
      name: 'Component Factory',
      description: '139 JSON configs. Universal component library with config chain.',
      tech_stack: ['React', 'Vite', 'TailwindCSS'],
      deployment_targets: ['cloudflare-pages'],
      status: 'healthy',
      owner: 'platform-team',
    },
    {
      node_id: 'pow3r-writer',
      node_type: 'service',
      name: 'pow3r.writer',
      description: 'Media generation service. Narrative, storyboard, image, audio, video.',
      tech_stack: ['React', 'Vite', 'Cloudflare Workers'],
      deployment_targets: ['cloudflare'],
      status: 'degraded',
      owner: 'platform-team',
    },
    {
      node_id: 'workflow-executor',
      node_type: 'workflow',
      name: 'Workflow Executor',
      description: 'Orchestrates deployment and validation workflows. Guardian gate enforcement.',
      tech_stack: ['Cloudflare Workers', 'Durable Objects'],
      deployment_targets: ['cloudflare'],
      status: 'healthy',
      owner: 'platform-team',
    },
  ],
  edges: [
    { edge_id: 'config-to-pkg', from_node: 'pow3r-config', to_node: 'pkg-knowledge', edge_type: 'data', permission_schema: { read: 'public' } },
    { edge_id: 'config-to-xmap', from_node: 'pow3r-config', to_node: 'xmap-server', edge_type: 'api', permission_schema: { read: 'public', execute: 'admin' } },
    { edge_id: 'config-to-guardian', from_node: 'pow3r-config', to_node: 'guardian-system', edge_type: 'control', permission_schema: { execute: 'admin' } },
    { edge_id: 'config-to-xsystem', from_node: 'pow3r-config', to_node: 'x-system', edge_type: 'event', permission_schema: { write: 'authenticated' } },
    { edge_id: 'config-to-pass', from_node: 'pow3r-config', to_node: 'pow3r-pass', edge_type: 'api', encryption_policy: 'tls-required' },
    { edge_id: 'director-to-config', from_node: 'director-agent', to_node: 'pow3r-config', edge_type: 'control', allowed_agents_roles: ['director'] },
    { edge_id: 'director-to-control', from_node: 'director-agent', to_node: 'pow3r-control', edge_type: 'control', allowed_agents_roles: ['director', 'architect-role'] },
    { edge_id: 'pkg-to-xmap', from_node: 'pkg-knowledge', to_node: 'xmap-server', edge_type: 'data' },
    { edge_id: 'guardian-to-executor', from_node: 'guardian-system', to_node: 'workflow-executor', edge_type: 'control' },
    { edge_id: 'xsystem-to-control', from_node: 'x-system', to_node: 'pow3r-control', edge_type: 'event' },
    { edge_id: 'executor-to-writer', from_node: 'workflow-executor', to_node: 'pow3r-writer', edge_type: 'control' },
    { edge_id: 'config-to-planmem', from_node: 'pow3r-config', to_node: 'plan-memory', edge_type: 'data' },
    { edge_id: 'control-to-xmap', from_node: 'pow3r-control', to_node: 'xmap-server', edge_type: 'api' },
    { edge_id: 'control-to-pkg', from_node: 'pow3r-control', to_node: 'pkg-knowledge', edge_type: 'api' },
    { edge_id: 'factory-to-config', from_node: 'component-factory', to_node: 'pow3r-config', edge_type: 'data' },
  ],
  workflows: [
    {
      workflow_id: 'wf-deploy-v1',
      workflow_type: 'deployment',
      steps: [
        { step_id: 'pkg-context', node: 'pkg-knowledge', action: 'query' },
        { step_id: 'x-system-start', node: 'x-system', action: 'log-start' },
        { step_id: 'guardian-check', node: 'guardian-system', action: 'validate-gates' },
        { step_id: 'build', node: 'pow3r-config', action: 'build' },
        { step_id: 'deploy', node: 'workflow-executor', action: 'deploy' },
        { step_id: 'test', node: 'workflow-executor', action: 'test-loop' },
        { step_id: 'push', node: 'pow3r-config', action: 'git-push' },
      ],
      retry_policy: { max_attempts: 3, backoff: 'exponential' },
      evidence_policy: { required_artifacts: ['screenshot', 'test-results'] },
      guardian_gates: ['contextLoadedGate', 'verifiableEvidenceGate', 'preDeploymentChecksGate'],
    },
    {
      workflow_id: 'wf-xmap-validation',
      workflow_type: 'validation',
      steps: [
        { step_id: 'validate-schema', node: 'xmap-server', action: 'validate' },
        { step_id: 'resolve-director', node: 'director-agent', action: 'resolve' },
      ],
      guardian_gates: ['contextLoadedGate'],
    },
  ],
  guardian: [
    { gate_id: 'contextLoadedGate', type: 'pre-commit', evaluation_policy: 'automated', required_evidence: [], action_on_fail: 'block' },
    { gate_id: 'verifiableEvidenceGate', type: 'pre-deploy', evaluation_policy: 'automated', required_evidence: ['screenshot', 'trace'], action_on_fail: 'block' },
    { gate_id: 'workflowTestsGate', type: 'pre-deploy', evaluation_policy: 'automated', required_evidence: ['test-results'], action_on_fail: 'block' },
    { gate_id: 'preDeploymentChecksGate', type: 'pre-deploy', evaluation_policy: 'automated', required_evidence: [], action_on_fail: 'block' },
    { gate_id: 'pow3rOrchestratorGate', type: 'pre-deploy', evaluation_policy: 'automated', action_on_fail: 'block' },
    { gate_id: 'documentationGate', type: 'pre-commit', evaluation_policy: 'mixed', action_on_fail: 'escalate' },
    { gate_id: 'behavioralTestRequiredGate', type: 'post-deploy', evaluation_policy: 'automated', required_evidence: ['behavioral-test'], action_on_fail: 'block' },
  ],
  validator: [
    {
      validator_id: 'director-agent-validator',
      rules: [{ rule_id: 'director-from-config', description: 'Director node must resolve from config.directorAgent' }],
      enforcement_mode: 'hard-block',
    },
  ],
  tests: [
    { test_id: 'wf-config-validation', type: 'contract', test_runner: 'vitest', required_result: { pass_threshold: 1 }, evidence_artifacts: ['test-output'] },
    { test_id: 'wf-xmap-validation', type: 'contract', test_runner: 'vitest', required_result: { pass_threshold: 1 }, evidence_artifacts: ['screenshot', 'trace'] },
  ],
  telemetry: [
    { metrics: ['/mcp/xmap/metrics'], logs: ['/mcp/xmap/logs'], traces: ['/mcp/xmap/traces'], retention_policy: { days: 90 } },
  ],
  config_controls: {
    patch_policy: 'delta',
    allowed_patch_ops: ['add', 'replace'],
    contract_tests_required: ['wf-config-validation'],
    manifest_lock: false,
  },
  provenance: [],
  agent_views: [
    { view_id: 'platform-overview', view_scope: { nodes: ['pow3r-config', 'pkg-knowledge', 'xmap-server', 'guardian-system', 'x-system', 'pow3r-pass'] }, ephemeral: false },
    { view_id: 'director-view', view_scope: { nodes: ['director-agent', 'pow3r-control', 'pow3r-config'] }, ephemeral: false },
  ],
  ui_contracts: [
    { viewer_bindings: { '3js_mapping': { node_id: 'position' }, director_resolution: 'config.directorAgent' }, evidence_capture_hooks: ['/mcp/xmap/evidence/capture'] },
  ],
  compliance: {
    compliance_score: 0.85,
    evidence_refs: [],
    compliance_status: 'compliant',
  },
}
