/**
 * pow3r.control - Sample XMAP v7 Data (Uber Master Complete)
 *
 * Purpose:
 * - Default graph with EVERYTHING: Uber Master + v7 XMAPs + data stores
 * - KV, D1, R2, Vectorize, PKG, MKB, PKB, TKB, PPG, Workflow Library, Component Library,
 *   PDAM, Plans, NOTESAI Vault, Prompt db, Chat db
 * - Sources: Pow3r_Uber_Master_Architecture_2026Q1, pow3r.platform.expansion.v7, wrangler.toml
 */
import type { XmapV7Config } from './types'

export const SAMPLE_CONFIG: XmapV7Config = {
  metadata: {
    id: 'pow3r-uber-master-v7',
    version: '1.0.0',
    created_at: '2026-02-26T00:00:00Z',
    created_by: 'pow3r.control',
    last_modified_at: '2026-02-26T00:00:00Z',
    last_modified_by: 'pow3r.control',
  },
  manifest: {
    manifest_id: 'pow3r-uber-master-manifest',
    manifest_version: '1.0.0',
    manifest_status: 'deployed',
    required_gates: [
      'contextLoadedGate',
      'verifiableEvidenceGate',
      'workflowTestsGate',
      'preDeploymentChecksGate',
    ],
  },
  directorAgent: 'agent-maxi',
  nodes: [
    // LAYER 1: Platform Core
    {
      node_id: 'pow3r-config',
      node_type: 'service',
      name: 'pow3r.config',
      description: 'Edge Orchestration Hub. Central config, docs, MCP. 28 MCP servers, 19 Guardian gates, 78+ workflows.',
      tech_stack: ['Cloudflare Workers', 'D1', 'R2', 'KV', 'Vectorize'],
      deployment_targets: ['cloudflare'],
      status: 'healthy',
      owner: 'platform-team',
      required_tests: ['wf-config-validation'],
      telemetry_endpoints: ['/mcp/xlog'],
    },
    // LAYER 2: Core Products
    {
      node_id: 'pow3r-abi',
      node_type: 'service',
      name: 'pow3r.abi',
      description: 'AI Director Dashboard. 3D/2D orchestration, agent monitoring, XMAP visualization.',
      tech_stack: ['React', 'Vite', 'Three.js', 'TailwindCSS', 'Zustand'],
      deployment_targets: ['cloudflare-pages'],
      status: 'healthy',
      owner: 'platform-team',
    },
    {
      node_id: 'pow3r-writer',
      node_type: 'service',
      name: 'pow3r.writer',
      description: 'Omnimedia Generation. Narrative, storyboard, image, audio, video. PDAM integration.',
      tech_stack: ['React', 'Vite', 'Cloudflare Workers'],
      deployment_targets: ['cloudflare'],
      status: 'degraded',
      owner: 'platform-team',
    },
    {
      node_id: 'pow3r-cloud',
      node_type: 'service',
      name: 'pow3r.cloud',
      description: 'Edge workflow orchestration. Durable Objects, D1+R2+KV.',
      tech_stack: ['Cloudflare Workers', 'Durable Objects', 'D1', 'R2', 'KV'],
      deployment_targets: ['cloudflare'],
      status: 'healthy',
      owner: 'platform-team',
    },
    {
      node_id: 'pow3r-canvas',
      node_type: 'service',
      name: 'pow3r.canvas',
      description: 'Real task management. Canvas visualization, workflow tracking.',
      tech_stack: ['React', 'Vite', 'TailwindCSS', 'Canvas API'],
      deployment_targets: ['cloudflare'],
      status: 'healthy',
      owner: 'platform-team',
    },
    {
      node_id: 'pow3r-xfiles',
      node_type: 'service',
      name: 'pow3r.xfiles',
      description: 'Bug reporting and case management. Self-healing, evidence, triage.',
      tech_stack: ['Cloudflare Workers', 'D1', 'KV'],
      deployment_targets: ['cloudflare'],
      status: 'healthy',
      owner: 'platform-team',
    },
    {
      node_id: 'pow3r-xmap',
      node_type: 'service',
      name: 'pow3r.xmap',
      description: 'Architecture visualization. Canvas generation, schema validation, repo scanning.',
      tech_stack: ['Cloudflare Workers', 'JSON Schema'],
      deployment_targets: ['cloudflare'],
      status: 'healthy',
      owner: 'platform-team',
    },
    // Supporting products
    {
      node_id: 'pow3r-build',
      node_type: 'service',
      name: 'pow3r.build',
      description: 'CI/CD pipeline with Guardian gates.',
      tech_stack: ['Cloudflare Workers'],
      deployment_targets: ['cloudflare'],
      status: 'healthy',
      owner: 'platform-team',
    },
    {
      node_id: 'pow3r-cashout',
      node_type: 'service',
      name: 'pow3r.cashout',
      description: 'Revenue and payment management.',
      tech_stack: [],
      deployment_targets: ['cloudflare'],
      status: 'healthy',
      owner: 'platform-team',
    },
    {
      node_id: 'pow3r-ddog',
      node_type: 'service',
      name: 'pow3r.ddog',
      description: 'Threat intelligence and OSINT platform.',
      tech_stack: [],
      deployment_targets: ['cloudflare'],
      status: 'healthy',
      owner: 'platform-team',
    },
    {
      node_id: 'pow3r-prompts',
      node_type: 'service',
      name: 'pow3r.prompts',
      description: 'Prompt management. Autonomous knowledge with MCP orchestrator.',
      tech_stack: [],
      deployment_targets: ['cloudflare'],
      status: 'deploying',
      owner: 'platform-team',
    },
    {
      node_id: 'pow3r-urvs',
      node_type: 'service',
      name: 'pow3r.urvs',
      description: 'Schemaverse visualization. Living knowledge graph.',
      tech_stack: [],
      deployment_targets: ['cloudflare'],
      status: 'healthy',
      owner: 'platform-team',
    },
    {
      node_id: 'pow3r-vault',
      node_type: 'gateway',
      name: 'pow3r.vault',
      description: 'Secrets management. Secure credential storage.',
      tech_stack: [],
      deployment_targets: ['cloudflare'],
      status: 'healthy',
      owner: 'platform-team',
    },
    // Power tools
    {
      node_id: 'power-jaime',
      node_type: 'service',
      name: 'power.jaime',
      description: 'J.ai.me - Personal AI assistant via Telegram.',
      tech_stack: ['Telegram', 'React'],
      deployment_targets: ['cloudflare'],
      status: 'healthy',
      owner: 'platform-team',
    },
    {
      node_id: 'power-obsidian',
      node_type: 'service',
      name: 'power.obsidian',
      description: 'Obsidian vault sync and canvas integration.',
      tech_stack: ['Obsidian', 'Canvas API'],
      deployment_targets: ['cloudflare'],
      status: 'healthy',
      owner: 'platform-team',
    },
    {
      node_id: 'power-pass',
      node_type: 'gateway',
      name: 'power.pass',
      description: 'Credential extension. Browser credential management.',
      tech_stack: ['Browser Extension'],
      deployment_targets: ['cloudflare'],
      status: 'healthy',
      owner: 'platform-team',
    },
    {
      node_id: 'power-components',
      node_type: 'component_factory',
      name: 'power.components',
      description: 'Component factory. 2D/3D, X-Surface, Data-as-Light. v1 blocking 6 products.',
      tech_stack: ['React', 'Three.js'],
      deployment_targets: ['cloudflare'],
      status: 'deploying',
      owner: 'platform-team',
    },
    // Infrastructure
    {
      node_id: 'cloudflare',
      node_type: 'service',
      name: 'Cloudflare',
      description: 'Workers, Pages, R2, D1, KV, Vectorize, Durable Objects, Queues.',
      tech_stack: ['Cloudflare Edge'],
      deployment_targets: [],
      status: 'healthy',
      owner: 'platform-team',
    },
    {
      node_id: 'abacusai',
      node_type: 'service',
      name: 'AbacusAI',
      description: 'Knowledge graphs, DeepAgents, Chat, Deep Research, Graph RAG.',
      tech_stack: ['AbacusAI Platform'],
      deployment_targets: [],
      status: 'healthy',
      owner: 'platform-team',
    },
    {
      node_id: 'github',
      node_type: 'service',
      name: 'GitHub',
      description: 'memorymusicllc org. 25+ repos. GitHub MCP.',
      tech_stack: ['GitHub'],
      deployment_targets: [],
      status: 'healthy',
      owner: 'platform-team',
    },
    // Agent workforce
    {
      node_id: 'agent-maxi',
      node_type: 'agent',
      name: 'Maxi Agent',
      description: 'Maximal capability. All 28 MCP servers. Director of Engineering.',
      tech_stack: ['Cloudflare Workers', 'Pass MCP'],
      deployment_targets: ['cloudflare'],
      status: 'validated',
      owner: 'platform-team',
      privileges: { read: 'public', propose: 'director', execute: 'director' },
    },
    {
      node_id: 'autogenesis',
      node_type: 'agent',
      name: 'AutoGenesis Engine',
      description: 'Agent-building-agent. Fleet spawning, lifecycle, task analysis.',
      tech_stack: [],
      deployment_targets: ['cloudflare'],
      status: 'healthy',
      owner: 'platform-team',
    },
    {
      node_id: 'shapeshifter',
      node_type: 'agent',
      name: 'Shapeshifter',
      description: 'Config mutator. Performance analysis, mutation proposals, Guardian validation.',
      tech_stack: [],
      deployment_targets: ['cloudflare'],
      status: 'healthy',
      owner: 'platform-team',
    },
    {
      node_id: 'super-agent',
      node_type: 'agent',
      name: 'J.ai.me Super Agent',
      description: 'Multi-modal (text, voice, vision). Cross-product synthesis MKB+PKG+TKB.',
      tech_stack: [],
      deployment_targets: ['cloudflare'],
      status: 'healthy',
      owner: 'platform-team',
    },
    // MCP servers
    {
      node_id: 'mcp-core',
      node_type: 'mcp_server',
      name: 'Core MCP',
      description: 'abi, pkg, pdam, orchestrator.',
      tech_stack: ['MCP'],
      deployment_targets: ['cloudflare'],
      status: 'healthy',
      owner: 'platform-team',
    },
    {
      node_id: 'mcp-xsystem',
      node_type: 'mcp_server',
      name: 'X-System MCP',
      description: 'xmap, x-plugin, x-files, xlog, xbugger.',
      tech_stack: ['MCP'],
      deployment_targets: ['cloudflare'],
      status: 'healthy',
      owner: 'platform-team',
    },
    // Data stores - KV
    {
      node_id: 'config-store',
      node_type: 'data',
      name: 'CONFIG_STORE',
      description: 'KV. XMAP configs, plan_memory:index, static fallback.',
      tech_stack: ['KV'],
      deployment_targets: ['cloudflare'],
      status: 'healthy',
      owner: 'platform-team',
    },
    {
      node_id: 'workflow-library',
      node_type: 'data',
      name: 'WORKFLOW_LIBRARY',
      description: 'KV. 109 workflow templates. Pattern learning.',
      tech_stack: ['KV'],
      deployment_targets: ['cloudflare'],
      status: 'healthy',
      owner: 'platform-team',
    },
    {
      node_id: 'kg-store',
      node_type: 'data',
      name: 'KG_STORE',
      description: 'KV. Knowledge graph metadata.',
      tech_stack: ['KV'],
      deployment_targets: ['cloudflare'],
      status: 'healthy',
      owner: 'platform-team',
    },
    {
      node_id: 'abi-orchestrator-kv',
      node_type: 'data',
      name: 'ABI_ORCHESTRATOR_KV',
      description: 'KV. Abi task state, workflow learning patterns.',
      tech_stack: ['KV'],
      deployment_targets: ['cloudflare'],
      status: 'healthy',
      owner: 'platform-team',
    },
    {
      node_id: 'mkb-store',
      node_type: 'data',
      name: 'MKB_STORE',
      description: 'KV. Master Knowledge Base. 4,751 NOTESAI files.',
      tech_stack: ['KV'],
      deployment_targets: ['cloudflare'],
      status: 'healthy',
      owner: 'platform-team',
    },
    {
      node_id: 'chat-store',
      node_type: 'data',
      name: 'CHAT_STORE',
      description: 'KV. Unified chat (Cursor, Abacus, Gemini, Grok, Telegram).',
      tech_stack: ['KV'],
      deployment_targets: ['cloudflare'],
      status: 'healthy',
      owner: 'platform-team',
    },
    {
      node_id: 'pkb-store',
      node_type: 'data',
      name: 'PKB_STORE',
      description: 'KV. Personal Knowledge Base. Obsidian vault.',
      tech_stack: ['KV'],
      deployment_targets: ['cloudflare'],
      status: 'healthy',
      owner: 'platform-team',
    },
    // Data stores - D1
    {
      node_id: 'analytics-db',
      node_type: 'data',
      name: 'ANALYTICS_DB',
      description: 'D1. pow3r-config-analytics.',
      tech_stack: ['D1'],
      deployment_targets: ['cloudflare'],
      status: 'healthy',
      owner: 'platform-team',
    },
    {
      node_id: 'abi-orchestrator-db',
      node_type: 'data',
      name: 'ABI_ORCHESTRATOR_DB',
      description: 'D1. Workflow pattern learning.',
      tech_stack: ['D1'],
      deployment_targets: ['cloudflare'],
      status: 'healthy',
      owner: 'platform-team',
    },
    {
      node_id: 'chat-history-db',
      node_type: 'data',
      name: 'CHAT_HISTORY_DB',
      description: 'D1. Queryable chat history SQL.',
      tech_stack: ['D1'],
      deployment_targets: ['cloudflare'],
      status: 'healthy',
      owner: 'platform-team',
    },
    // Data stores - R2
    {
      node_id: 'evidence-store',
      node_type: 'data',
      name: 'EVIDENCE_STORE',
      description: 'R2. Screenshots, traces, evidence.',
      tech_stack: ['R2'],
      deployment_targets: ['cloudflare'],
      status: 'healthy',
      owner: 'platform-team',
    },
    {
      node_id: 'pdam-assets',
      node_type: 'data',
      name: 'PDAM_ASSETS',
      description: 'R2. Digital assets, projects.',
      tech_stack: ['R2'],
      deployment_targets: ['cloudflare'],
      status: 'healthy',
      owner: 'platform-team',
    },
    {
      node_id: 'library-store',
      node_type: 'data',
      name: 'LIBRARY_STORE',
      description: 'R2. PIMP/PDAM UI, component library assets.',
      tech_stack: ['R2'],
      deployment_targets: ['cloudflare'],
      status: 'healthy',
      owner: 'platform-team',
    },
    // Data stores - Vectorize
    {
      node_id: 'pkg-index',
      node_type: 'data',
      name: 'PKG_INDEX',
      description: 'Vectorize. 3,127 doc embeddings. Product Knowledge Graph.',
      tech_stack: ['Vectorize'],
      deployment_targets: ['cloudflare'],
      status: 'healthy',
      owner: 'platform-team',
    },
    {
      node_id: 'mkb-index',
      node_type: 'data',
      name: 'MKB_INDEX',
      description: 'Vectorize. Master KB embeddings.',
      tech_stack: ['Vectorize'],
      deployment_targets: ['cloudflare'],
      status: 'healthy',
      owner: 'platform-team',
    },
    {
      node_id: 'pkb-index',
      node_type: 'data',
      name: 'PKB_INDEX',
      description: 'Vectorize. Personal KB. Obsidian vault 768-dim.',
      tech_stack: ['Vectorize'],
      deployment_targets: ['cloudflare'],
      status: 'healthy',
      owner: 'platform-team',
    },
    {
      node_id: 'ppg-index',
      node_type: 'data',
      name: 'PPG_INDEX',
      description: 'Vectorize. Pow3r Pitch Graph RAG.',
      tech_stack: ['Vectorize'],
      deployment_targets: ['cloudflare'],
      status: 'healthy',
      owner: 'platform-team',
    },
    // Observers / system
    {
      node_id: 'guardian-system',
      node_type: 'observer',
      name: 'Guardian System',
      description: '19 gates, 12 articles. Constitutional enforcement.',
      tech_stack: ['Guardian Gates'],
      deployment_targets: ['cloudflare'],
      status: 'healthy',
      owner: 'platform-team',
    },
    {
      node_id: 'x-system',
      node_type: 'observer',
      name: 'X-System',
      description: 'X-Plugin, X-Log, X-Files, X-Stream, JSON Chain.',
      tech_stack: ['Cloudflare Workers', 'D1'],
      deployment_targets: ['cloudflare'],
      status: 'healthy',
      owner: 'platform-team',
      telemetry_endpoints: ['/mcp/xplugin', '/mcp/xlog', '/mcp/xfiles', '/mcp/xstream'],
    },
    {
      node_id: 'pow3r-pass',
      node_type: 'gateway',
      name: 'Pow3r Pass',
      description: 'Credential management. PASS_KEY, ACL.',
      tech_stack: ['Cloudflare Workers', 'KV'],
      deployment_targets: ['cloudflare'],
      status: 'healthy',
      owner: 'platform-team',
      privileges: { read: 'authenticated', write: 'admin' },
    },
    {
      node_id: 'plan-memory',
      node_type: 'data',
      name: 'Plan Memory',
      description: 'plan_memory:index in CONFIG_STORE. Canonical plan index.',
      tech_stack: ['KV', 'CONFIG_STORE'],
      deployment_targets: ['cloudflare'],
      status: 'healthy',
      owner: 'platform-team',
    },
    {
      node_id: 'pow3r-control',
      node_type: 'ui',
      name: 'pow3r.control',
      description: 'Omnimedia control. 3D/2D XMAP, PIMP, OSC layout.',
      tech_stack: ['React', 'Vite', 'TailwindCSS', 'Three.js', 'R3F'],
      deployment_targets: ['cloudflare-pages'],
      status: 'deploying',
      owner: 'platform-team',
    },
    {
      node_id: 'component-factory',
      node_type: 'component_factory',
      name: 'Component Library',
      description: '139 JSON configs. config.superbots.link/library.',
      tech_stack: ['React', 'Vite', 'TailwindCSS'],
      deployment_targets: ['cloudflare-pages'],
      status: 'healthy',
      owner: 'platform-team',
    },
    {
      node_id: 'workflow-executor',
      node_type: 'workflow',
      name: 'Workflow Executor',
      description: 'Deployment and validation. Guardian gate enforcement.',
      tech_stack: ['Cloudflare Workers', 'Durable Objects'],
      deployment_targets: ['cloudflare'],
      status: 'healthy',
      owner: 'platform-team',
    },
    {
      node_id: 'notesai-vault',
      node_type: 'data',
      name: 'NOTESAI Vault',
      description: 'Cloud copy of local Obsidian vault. MKB/PKB source.',
      tech_stack: ['Obsidian', 'MKB_INDEX', 'PKB_INDEX'],
      deployment_targets: ['cloudflare'],
      status: 'healthy',
      owner: 'platform-team',
    },
  ],
  edges: [
    // Config hub
    { edge_id: 'config-to-abi', from_node: 'pow3r-config', to_node: 'pow3r-abi', edge_type: 'api', permission_schema: { read: 'public' } },
    { edge_id: 'config-to-writer', from_node: 'pow3r-config', to_node: 'pow3r-writer', edge_type: 'api', permission_schema: { read: 'public' } },
    { edge_id: 'config-to-cloud', from_node: 'pow3r-config', to_node: 'pow3r-cloud', edge_type: 'control', permission_schema: { execute: 'admin' } },
    { edge_id: 'config-to-canvas', from_node: 'pow3r-config', to_node: 'pow3r-canvas', edge_type: 'api' },
    { edge_id: 'config-to-xfiles', from_node: 'pow3r-config', to_node: 'pow3r-xfiles', edge_type: 'event' },
    { edge_id: 'config-to-xmap', from_node: 'pow3r-config', to_node: 'pow3r-xmap', edge_type: 'api' },
    { edge_id: 'config-to-guardian', from_node: 'pow3r-config', to_node: 'guardian-system', edge_type: 'control' },
    { edge_id: 'config-to-xsystem', from_node: 'pow3r-config', to_node: 'x-system', edge_type: 'event' },
    { edge_id: 'config-to-pass', from_node: 'pow3r-config', to_node: 'pow3r-pass', edge_type: 'api', encryption_policy: 'tls-required' },
    { edge_id: 'config-to-cloudflare', from_node: 'pow3r-config', to_node: 'cloudflare', edge_type: 'control' },
    { edge_id: 'config-to-abacus', from_node: 'pow3r-config', to_node: 'abacusai', edge_type: 'api' },
    { edge_id: 'config-to-agent-maxi', from_node: 'pow3r-config', to_node: 'agent-maxi', edge_type: 'control' },
    { edge_id: 'config-to-mcp-core', from_node: 'pow3r-config', to_node: 'mcp-core', edge_type: 'api' },
    { edge_id: 'config-to-planmem', from_node: 'pow3r-config', to_node: 'plan-memory', edge_type: 'data' },
    { edge_id: 'config-to-config-store', from_node: 'pow3r-config', to_node: 'config-store', edge_type: 'data' },
    { edge_id: 'config-to-workflow-library', from_node: 'pow3r-config', to_node: 'workflow-library', edge_type: 'data' },
    // Agents
    { edge_id: 'agent-maxi-to-control', from_node: 'agent-maxi', to_node: 'pow3r-control', edge_type: 'control', allowed_agents_roles: ['director'] },
    { edge_id: 'abi-to-autogenesis', from_node: 'pow3r-abi', to_node: 'autogenesis', edge_type: 'control' },
    { edge_id: 'shapeshifter-to-autogenesis', from_node: 'shapeshifter', to_node: 'autogenesis', edge_type: 'control' },
    { edge_id: 'agent-maxi-to-xsystem', from_node: 'agent-maxi', to_node: 'mcp-xsystem', edge_type: 'event' },
    // Data flow
    { edge_id: 'config-to-pkg-index', from_node: 'pow3r-config', to_node: 'pkg-index', edge_type: 'data' },
    { edge_id: 'config-to-mkb-store', from_node: 'pow3r-config', to_node: 'mkb-store', edge_type: 'data' },
    { edge_id: 'config-to-pkb-store', from_node: 'pow3r-config', to_node: 'pkb-store', edge_type: 'data' },
    { edge_id: 'config-to-chat-store', from_node: 'pow3r-config', to_node: 'chat-store', edge_type: 'data' },
    { edge_id: 'writer-to-pdam-assets', from_node: 'pow3r-writer', to_node: 'pdam-assets', edge_type: 'data' },
    { edge_id: 'writer-to-ppg-index', from_node: 'pow3r-writer', to_node: 'ppg-index', edge_type: 'data' },
    { edge_id: 'xfiles-to-evidence-store', from_node: 'pow3r-xfiles', to_node: 'evidence-store', edge_type: 'data' },
    { edge_id: 'guardian-to-executor', from_node: 'guardian-system', to_node: 'workflow-executor', edge_type: 'control' },
    { edge_id: 'executor-to-writer', from_node: 'workflow-executor', to_node: 'pow3r-writer', edge_type: 'control' },
    { edge_id: 'executor-to-cloud', from_node: 'workflow-executor', to_node: 'pow3r-cloud', edge_type: 'control' },
    { edge_id: 'xsystem-to-control', from_node: 'x-system', to_node: 'pow3r-control', edge_type: 'event' },
    { edge_id: 'control-to-pkg-index', from_node: 'pow3r-control', to_node: 'pkg-index', edge_type: 'api' },
    { edge_id: 'control-to-config-store', from_node: 'pow3r-control', to_node: 'config-store', edge_type: 'api' },
    { edge_id: 'factory-to-config', from_node: 'component-factory', to_node: 'pow3r-config', edge_type: 'data' },
    { edge_id: 'cloudflare-to-github', from_node: 'cloudflare', to_node: 'github', edge_type: 'control' },
    { edge_id: 'power-obsidian-to-notesai', from_node: 'power-obsidian', to_node: 'notesai-vault', edge_type: 'data' },
    { edge_id: 'mkb-store-to-mkb-index', from_node: 'mkb-store', to_node: 'mkb-index', edge_type: 'data' },
    { edge_id: 'pkb-store-to-pkb-index', from_node: 'pkb-store', to_node: 'pkb-index', edge_type: 'data' },
    { edge_id: 'super-agent-to-pkg', from_node: 'super-agent', to_node: 'pkg-index', edge_type: 'api' },
  ],
  workflows: [
    {
      workflow_id: 'wf-deploy-v1',
      workflow_type: 'deployment',
      steps: [
        { step_id: 'pkg-context', node: 'pkg-index', action: 'query' },
        { step_id: 'x-system-start', node: 'x-system', action: 'log-start' },
        { step_id: 'guardian-check', node: 'guardian-system', action: 'validate-gates' },
        { step_id: 'build', node: 'pow3r-config', action: 'build' },
        { step_id: 'deploy', node: 'workflow-executor', action: 'deploy' },
        { step_id: 'test', node: 'workflow-executor', action: 'test-loop' },
        { step_id: 'push', node: 'pow3r-config', action: 'git-push' },
      ],
      retry_policy: { max_attempts: 3, backoff: 'exponential' },
      evidence_policy: { required_artifacts: ['screenshot', 'test-results'] },
      guardian_gates: ['contextLoadedGate', 'verifiableEvidenceGate', 'preDeploymentChecksGate'],
    },
    {
      workflow_id: 'wf-xmap-validation',
      workflow_type: 'validation',
      steps: [
        { step_id: 'validate-schema', node: 'pow3r-xmap', action: 'validate' },
        { step_id: 'resolve-director', node: 'agent-maxi', action: 'resolve' },
      ],
      guardian_gates: ['contextLoadedGate'],
    },
  ],
  guardian: [
    { gate_id: 'contextLoadedGate', type: 'pre-commit', evaluation_policy: 'automated', required_evidence: [], action_on_fail: 'block' },
    { gate_id: 'verifiableEvidenceGate', type: 'pre-deploy', evaluation_policy: 'automated', required_evidence: ['screenshot', 'trace'], action_on_fail: 'block' },
    { gate_id: 'workflowTestsGate', type: 'pre-deploy', evaluation_policy: 'automated', required_evidence: ['test-results'], action_on_fail: 'block' },
    { gate_id: 'preDeploymentChecksGate', type: 'pre-deploy', evaluation_policy: 'automated', required_evidence: [], action_on_fail: 'block' },
    { gate_id: 'pow3rOrchestratorGate', type: 'pre-deploy', evaluation_policy: 'automated', action_on_fail: 'block' },
    { gate_id: 'documentationGate', type: 'pre-commit', evaluation_policy: 'mixed', action_on_fail: 'escalate' },
    { gate_id: 'behavioralTestRequiredGate', type: 'post-deploy', evaluation_policy: 'automated', required_evidence: ['behavioral-test'], action_on_fail: 'block' },
  ],
  validator: [
    {
      validator_id: 'director-agent-validator',
      rules: [{ rule_id: 'director-from-config', description: 'Director node must resolve from config.directorAgent' }],
      enforcement_mode: 'hard-block',
    },
  ],
  tests: [
    { test_id: 'wf-config-validation', type: 'contract', test_runner: 'vitest', required_result: { pass_threshold: 1 }, evidence_artifacts: ['test-output'] },
    { test_id: 'wf-xmap-validation', type: 'contract', test_runner: 'vitest', required_result: { pass_threshold: 1 }, evidence_artifacts: ['screenshot', 'trace'] },
  ],
  telemetry: [
    { metrics: ['/mcp/xmap/metrics'], logs: ['/mcp/xmap/logs'], traces: ['/mcp/xmap/traces'], retention_policy: { days: 90 } },
  ],
  config_controls: {
    patch_policy: 'delta',
    allowed_patch_ops: ['add', 'replace'],
    contract_tests_required: ['wf-config-validation'],
    manifest_lock: false,
  },
  provenance: [],
  agent_views: [
    { view_id: 'platform-overview', view_scope: { nodes: ['pow3r-config', 'pkg-index', 'pow3r-xmap', 'guardian-system', 'x-system', 'pow3r-pass'] }, ephemeral: false },
    { view_id: 'director-view', view_scope: { nodes: ['agent-maxi', 'pow3r-control', 'pow3r-config'] }, ephemeral: false },
    { view_id: 'data-stores', view_scope: { nodes: ['config-store', 'workflow-library', 'pkg-index', 'mkb-store', 'pkb-store', 'chat-store', 'notesai-vault'] }, ephemeral: false },
  ],
  ui_contracts: [
    { viewer_bindings: { '3js_mapping': { node_id: 'position' }, director_resolution: 'config.directorAgent' }, evidence_capture_hooks: ['/mcp/xmap/evidence/capture'] },
  ],
  compliance: {
    compliance_score: 0.85,
    evidence_refs: [],
    compliance_status: 'compliant',
  },
}
